package com.black.blog.back.baseInfo.model;

import com.black.blog.back.baseInfo.model.base.BaseBiDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BiDict extends BaseBiDict<BiDict> {
	public static final BiDict dao = new BiDict().dao();
}
