package com.black.blog.back.baseInfo.model;

import com.black.blog.back.baseInfo.model.base.BaseBiRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BiRole extends BaseBiRole<BiRole> {
	public static final BiRole dao = new BiRole().dao();
}
