package com.black.blog.back.baseInfo.model;

import com.black.blog.back.baseInfo.model.base.BaseBiUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BiUserRole extends BaseBiUserRole<BiUserRole> {
	public static final BiUserRole dao = new BiUserRole().dao();
}
