package com.black.blog.back.blogSys.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _BlogSysMappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _BlogSysMappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("bs_ad", "ID", BsAd.class);
		arp.addMapping("bs_article", "ID", BsArticle.class);
		arp.addMapping("bs_article_sort", "ID", BsArticleSort.class);
		arp.addMapping("bs_attention", "ID", BsAttention.class);
		arp.addMapping("bs_blog_info", "ID", BsBlogInfo.class);
		arp.addMapping("bs_friend", "ID", BsFriend.class);
		arp.addMapping("bs_friendly_link", "ID", BsFriendlyLink.class);
		arp.addMapping("bs_group", "ID", BsGroup.class);
		arp.addMapping("bs_mood_saysay", "ID", BsMoodSaysay.class);
		arp.addMapping("bs_photo_sort", "ID", BsPhotoSort.class);
		arp.addMapping("bs_photos", "ID", BsPhotos.class);
		arp.addMapping("bs_rank", "ID", BsRank.class);
		arp.addMapping("bs_secret_msg", "ID", BsSecretMsg.class);
		arp.addMapping("bs_stay_msg", "ID", BsStayMsg.class);
		arp.addMapping("bs_sys_msg", "ID", BsSysMsg.class);
		arp.addMapping("bs_user", "ID", BsUser.class);
		arp.addMapping("bs_user_comm", "ID", BsUserComm.class);
		arp.addMapping("bs_visitor", "ID", BsVisitor.class);
	}
}

