package com.black.blog.back.blogSys.model;

import com.black.blog.back.blogSys.model.base.BaseBsAd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BsAd extends BaseBsAd<BsAd> {
	public static final BsAd dao = new BsAd().dao();
}
