package com.black.blog.back.blogSys.model;

import com.black.blog.back.blogSys.model.base.BaseBsArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BsArticle extends BaseBsArticle<BsArticle> {
	public static final BsArticle dao = new BsArticle().dao();
}
