package com.black.blog.back.blogSys.model;

import com.black.blog.back.blogSys.model.base.BaseBsArticleSort;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BsArticleSort extends BaseBsArticleSort<BsArticleSort> {
	public static final BsArticleSort dao = new BsArticleSort().dao();
}
