package com.black.blog.back.blogSys.model;

import com.black.blog.back.blogSys.model.base.BaseBsAttention;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BsAttention extends BaseBsAttention<BsAttention> {
	public static final BsAttention dao = new BsAttention().dao();
}
