package com.black.blog.back.blogSys.model;

import com.black.blog.back.blogSys.model.base.BaseBsBlogInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BsBlogInfo extends BaseBsBlogInfo<BsBlogInfo> {
	public static final BsBlogInfo dao = new BsBlogInfo().dao();
}
