package com.black.blog.back.blogSys.model;

import com.black.blog.back.blogSys.model.base.BaseBsFriend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BsFriend extends BaseBsFriend<BsFriend> {
	public static final BsFriend dao = new BsFriend().dao();
}
