package com.black.blog.back.blogSys.model;

import com.black.blog.back.blogSys.model.base.BaseBsFriendlyLink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BsFriendlyLink extends BaseBsFriendlyLink<BsFriendlyLink> {
	public static final BsFriendlyLink dao = new BsFriendlyLink().dao();
}
