package com.black.blog.back.blogSys.model;

import com.black.blog.back.blogSys.model.base.BaseBsGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BsGroup extends BaseBsGroup<BsGroup> {
	public static final BsGroup dao = new BsGroup().dao();
}
