package com.black.blog.back.blogSys.model;

import com.black.blog.back.blogSys.model.base.BaseBsMoodSaysay;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BsMoodSaysay extends BaseBsMoodSaysay<BsMoodSaysay> {
	public static final BsMoodSaysay dao = new BsMoodSaysay().dao();
}
