package com.black.blog.back.blogSys.model;

import com.black.blog.back.blogSys.model.base.BaseBsPhotos;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BsPhotos extends BaseBsPhotos<BsPhotos> {
	public static final BsPhotos dao = new BsPhotos().dao();
}
