package com.black.blog.back.blogSys.model;

import com.black.blog.back.blogSys.model.base.BaseBsPhotoSort;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BsPhotoSort extends BaseBsPhotoSort<BsPhotoSort> {
	public static final BsPhotoSort dao = new BsPhotoSort().dao();
}
