package com.black.blog.back.blogSys.model;

import com.black.blog.back.blogSys.model.base.BaseBsRank;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BsRank extends BaseBsRank<BsRank> {
	public static final BsRank dao = new BsRank().dao();
}
