package com.black.blog.back.blogSys.model;

import com.black.blog.back.blogSys.model.base.BaseBsSecretMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BsSecretMsg extends BaseBsSecretMsg<BsSecretMsg> {
	public static final BsSecretMsg dao = new BsSecretMsg().dao();
}
