package com.black.blog.back.blogSys.model;

import com.black.blog.back.blogSys.model.base.BaseBsStayMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BsStayMsg extends BaseBsStayMsg<BsStayMsg> {
	public static final BsStayMsg dao = new BsStayMsg().dao();
}
