package com.black.blog.back.blogSys.model;

import com.black.blog.back.blogSys.model.base.BaseBsSysMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BsSysMsg extends BaseBsSysMsg<BsSysMsg> {
	public static final BsSysMsg dao = new BsSysMsg().dao();
}
