package com.black.blog.back.blogSys.model;

import com.black.blog.back.blogSys.model.base.BaseBsUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BsUser extends BaseBsUser<BsUser> {
	public static final BsUser dao = new BsUser().dao();
}
