package com.black.blog.back.blogSys.model;

import com.black.blog.back.blogSys.model.base.BaseBsUserComm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BsUserComm extends BaseBsUserComm<BsUserComm> {
	public static final BsUserComm dao = new BsUserComm().dao();
}
