package com.black.blog.back.blogSys.model;

import com.black.blog.back.blogSys.model.base.BaseBsVisitor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BsVisitor extends BaseBsVisitor<BsVisitor> {
	public static final BsVisitor dao = new BsVisitor().dao();
}
