package com.black.blog.back.blogSys.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBsVisitor<M extends BaseBsVisitor<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setFkBsUserBeVisi(java.lang.String fkBsUserBeVisi) {
		set("FK_BS_USER_BE_VISI", fkBsUserBeVisi);
		return (M)this;
	}
	
	public java.lang.String getFkBsUserBeVisi() {
		return getStr("FK_BS_USER_BE_VISI");
	}

	public M setFkBsUserDoVisi(java.lang.String fkBsUserDoVisi) {
		set("FK_BS_USER_DO_VISI", fkBsUserDoVisi);
		return (M)this;
	}
	
	public java.lang.String getFkBsUserDoVisi() {
		return getStr("FK_BS_USER_DO_VISI");
	}

	public M setVisiModel(java.lang.String visiModel) {
		set("VISI_MODEL", visiModel);
		return (M)this;
	}
	
	public java.lang.String getVisiModel() {
		return getStr("VISI_MODEL");
	}

	public M setFkTableId(java.lang.String fkTableId) {
		set("FK_TABLE_ID", fkTableId);
		return (M)this;
	}
	
	public java.lang.String getFkTableId() {
		return getStr("FK_TABLE_ID");
	}

	public M setVisiTime(java.lang.String visiTime) {
		set("VISI_TIME", visiTime);
		return (M)this;
	}
	
	public java.lang.String getVisiTime() {
		return getStr("VISI_TIME");
	}

	public M setVisitorIp(java.lang.String visitorIp) {
		set("VISITOR_IP", visitorIp);
		return (M)this;
	}
	
	public java.lang.String getVisitorIp() {
		return getStr("VISITOR_IP");
	}

}
