package com.black.blog.back.blogSys.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBsMoodSaysay<M extends BaseBsMoodSaysay<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setFkBsUser(java.lang.String fkBsUser) {
		set("FK_BS_USER", fkBsUser);
		return (M)this;
	}
	
	public java.lang.String getFkBsUser() {
		return getStr("FK_BS_USER");
	}

	public M setPublishStatus(java.lang.String publishStatus) {
		set("PUBLISH_STATUS", publishStatus);
		return (M)this;
	}
	
	public java.lang.String getPublishStatus() {
		return getStr("PUBLISH_STATUS");
	}

	public M setPublishTime(java.lang.String publishTime) {
		set("PUBLISH_TIME", publishTime);
		return (M)this;
	}
	
	public java.lang.String getPublishTime() {
		return getStr("PUBLISH_TIME");
	}

	public M setPublishIp(java.lang.String publishIp) {
		set("PUBLISH_IP", publishIp);
		return (M)this;
	}
	
	public java.lang.String getPublishIp() {
		return getStr("PUBLISH_IP");
	}

	public M setSaysayModel(java.lang.String saysayModel) {
		set("SAYSAY_MODEL", saysayModel);
		return (M)this;
	}
	
	public java.lang.String getSaysayModel() {
		return getStr("SAYSAY_MODEL");
	}

	public M setSaysayContant(java.lang.String saysayContant) {
		set("SAYSAY_CONTANT", saysayContant);
		return (M)this;
	}
	
	public java.lang.String getSaysayContant() {
		return getStr("SAYSAY_CONTANT");
	}

	public M setTopStatus(java.lang.String topStatus) {
		set("TOP_STATUS", topStatus);
		return (M)this;
	}
	
	public java.lang.String getTopStatus() {
		return getStr("TOP_STATUS");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("CREATE_TIME", createTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return getStr("CREATE_TIME");
	}

	public M setCreateUserId(java.lang.String createUserId) {
		set("CREATE_USER_ID", createUserId);
		return (M)this;
	}
	
	public java.lang.String getCreateUserId() {
		return getStr("CREATE_USER_ID");
	}

	public M setModifyTime(java.lang.String modifyTime) {
		set("MODIFY_TIME", modifyTime);
		return (M)this;
	}
	
	public java.lang.String getModifyTime() {
		return getStr("MODIFY_TIME");
	}

	public M setModifyUserId(java.lang.String modifyUserId) {
		set("MODIFY_USER_ID", modifyUserId);
		return (M)this;
	}
	
	public java.lang.String getModifyUserId() {
		return getStr("MODIFY_USER_ID");
	}

}
