package com.black.blog.back.blogSys.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBsBlogInfo<M extends BaseBsBlogInfo<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setFkBsUser(java.lang.String fkBsUser) {
		set("FK_BS_USER", fkBsUser);
		return (M)this;
	}
	
	public java.lang.String getFkBsUser() {
		return getStr("FK_BS_USER");
	}

	public M setBlogTitle(java.lang.String blogTitle) {
		set("BLOG_TITLE", blogTitle);
		return (M)this;
	}
	
	public java.lang.String getBlogTitle() {
		return getStr("BLOG_TITLE");
	}

	public M setBlogKeyword(java.lang.String blogKeyword) {
		set("BLOG_KEYWORD", blogKeyword);
		return (M)this;
	}
	
	public java.lang.String getBlogKeyword() {
		return getStr("BLOG_KEYWORD");
	}

	public M setBlogDesc(java.lang.String blogDesc) {
		set("BLOG_DESC", blogDesc);
		return (M)this;
	}
	
	public java.lang.String getBlogDesc() {
		return getStr("BLOG_DESC");
	}

	public M setBlogName(java.lang.String blogName) {
		set("BLOG_NAME", blogName);
		return (M)this;
	}
	
	public java.lang.String getBlogName() {
		return getStr("BLOG_NAME");
	}

	public M setBgImgAddr(java.lang.String bgImgAddr) {
		set("BG_IMG_ADDR", bgImgAddr);
		return (M)this;
	}
	
	public java.lang.String getBgImgAddr() {
		return getStr("BG_IMG_ADDR");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("CREATE_TIME", createTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return getStr("CREATE_TIME");
	}

	public M setCreateUserId(java.lang.String createUserId) {
		set("CREATE_USER_ID", createUserId);
		return (M)this;
	}
	
	public java.lang.String getCreateUserId() {
		return getStr("CREATE_USER_ID");
	}

	public M setModifyTime(java.lang.String modifyTime) {
		set("MODIFY_TIME", modifyTime);
		return (M)this;
	}
	
	public java.lang.String getModifyTime() {
		return getStr("MODIFY_TIME");
	}

	public M setModifyUserId(java.lang.String modifyUserId) {
		set("MODIFY_USER_ID", modifyUserId);
		return (M)this;
	}
	
	public java.lang.String getModifyUserId() {
		return getStr("MODIFY_USER_ID");
	}

}
