package com.black.blog.back.blogSys.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBsSysMsg<M extends BaseBsSysMsg<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setFkBiSysMsg(java.lang.String fkBiSysMsg) {
		set("FK_BI_SYS_MSG", fkBiSysMsg);
		return (M)this;
	}
	
	public java.lang.String getFkBiSysMsg() {
		return getStr("FK_BI_SYS_MSG");
	}

	public M setFkBsUser(java.lang.String fkBsUser) {
		set("FK_BS_USER", fkBsUser);
		return (M)this;
	}
	
	public java.lang.String getFkBsUser() {
		return getStr("FK_BS_USER");
	}

	public M setFkBsGroup(java.lang.String fkBsGroup) {
		set("FK_BS_GROUP", fkBsGroup);
		return (M)this;
	}
	
	public java.lang.String getFkBsGroup() {
		return getStr("FK_BS_GROUP");
	}

	public M setReadStatus(java.lang.String readStatus) {
		set("READ_STATUS", readStatus);
		return (M)this;
	}
	
	public java.lang.String getReadStatus() {
		return getStr("READ_STATUS");
	}

	public M setNoticeTitle(java.lang.String noticeTitle) {
		set("NOTICE_TITLE", noticeTitle);
		return (M)this;
	}
	
	public java.lang.String getNoticeTitle() {
		return getStr("NOTICE_TITLE");
	}

	public M setNoticeContant(java.lang.String noticeContant) {
		set("NOTICE_CONTANT", noticeContant);
		return (M)this;
	}
	
	public java.lang.String getNoticeContant() {
		return getStr("NOTICE_CONTANT");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("CREATE_TIME", createTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return getStr("CREATE_TIME");
	}

	public M setCreateUserId(java.lang.String createUserId) {
		set("CREATE_USER_ID", createUserId);
		return (M)this;
	}
	
	public java.lang.String getCreateUserId() {
		return getStr("CREATE_USER_ID");
	}

}
