package com.black.blog.back.blogSys.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBsArticleSort<M extends BaseBsArticleSort<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setFkBsUser(java.lang.String fkBsUser) {
		set("FK_BS_USER", fkBsUser);
		return (M)this;
	}
	
	public java.lang.String getFkBsUser() {
		return getStr("FK_BS_USER");
	}

	public M setClassifyName(java.lang.String classifyName) {
		set("CLASSIFY_NAME", classifyName);
		return (M)this;
	}
	
	public java.lang.String getClassifyName() {
		return getStr("CLASSIFY_NAME");
	}

}
