package com.black.blog.back.blogSys.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBsStayMsg<M extends BaseBsStayMsg<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setFkBsUserSelf(java.lang.String fkBsUserSelf) {
		set("FK_BS_USER_SELF", fkBsUserSelf);
		return (M)this;
	}
	
	public java.lang.String getFkBsUserSelf() {
		return getStr("FK_BS_USER_SELF");
	}

	public M setFkBsUserStay(java.lang.String fkBsUserStay) {
		set("FK_BS_USER_STAY", fkBsUserStay);
		return (M)this;
	}
	
	public java.lang.String getFkBsUserStay() {
		return getStr("FK_BS_USER_STAY");
	}

	public M setStayContant(java.lang.String stayContant) {
		set("STAY_CONTANT", stayContant);
		return (M)this;
	}
	
	public java.lang.String getStayContant() {
		return getStr("STAY_CONTANT");
	}

	public M setStayIp(java.lang.String stayIp) {
		set("STAY_IP", stayIp);
		return (M)this;
	}
	
	public java.lang.String getStayIp() {
		return getStr("STAY_IP");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("CREATE_TIME", createTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return getStr("CREATE_TIME");
	}

	public M setCreateUserId(java.lang.String createUserId) {
		set("CREATE_USER_ID", createUserId);
		return (M)this;
	}
	
	public java.lang.String getCreateUserId() {
		return getStr("CREATE_USER_ID");
	}

	public M setModifyTime(java.lang.String modifyTime) {
		set("MODIFY_TIME", modifyTime);
		return (M)this;
	}
	
	public java.lang.String getModifyTime() {
		return getStr("MODIFY_TIME");
	}

	public M setModifyUserId(java.lang.String modifyUserId) {
		set("MODIFY_USER_ID", modifyUserId);
		return (M)this;
	}
	
	public java.lang.String getModifyUserId() {
		return getStr("MODIFY_USER_ID");
	}

}
