package com.black.blog.back.blogSys.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBsFriendlyLink<M extends BaseBsFriendlyLink<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setLinkName(java.lang.String linkName) {
		set("LINK_NAME", linkName);
		return (M)this;
	}
	
	public java.lang.String getLinkName() {
		return getStr("LINK_NAME");
	}

	public M setLinkAddr(java.lang.String linkAddr) {
		set("LINK_ADDR", linkAddr);
		return (M)this;
	}
	
	public java.lang.String getLinkAddr() {
		return getStr("LINK_ADDR");
	}

	public M setLinkLogo(java.lang.String linkLogo) {
		set("LINK_LOGO", linkLogo);
		return (M)this;
	}
	
	public java.lang.String getLinkLogo() {
		return getStr("LINK_LOGO");
	}

	public M setShowOrder(java.lang.Integer showOrder) {
		set("SHOW_ORDER", showOrder);
		return (M)this;
	}
	
	public java.lang.Integer getShowOrder() {
		return getInt("SHOW_ORDER");
	}

	public M setUseStatus(java.lang.String useStatus) {
		set("USE_STATUS", useStatus);
		return (M)this;
	}
	
	public java.lang.String getUseStatus() {
		return getStr("USE_STATUS");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("CREATE_TIME", createTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return getStr("CREATE_TIME");
	}

	public M setCreateUserId(java.lang.String createUserId) {
		set("CREATE_USER_ID", createUserId);
		return (M)this;
	}
	
	public java.lang.String getCreateUserId() {
		return getStr("CREATE_USER_ID");
	}

	public M setModifyTime(java.lang.String modifyTime) {
		set("MODIFY_TIME", modifyTime);
		return (M)this;
	}
	
	public java.lang.String getModifyTime() {
		return getStr("MODIFY_TIME");
	}

	public M setModifyUserId(java.lang.String modifyUserId) {
		set("MODIFY_USER_ID", modifyUserId);
		return (M)this;
	}
	
	public java.lang.String getModifyUserId() {
		return getStr("MODIFY_USER_ID");
	}

}
