package com.black.blog.back.blogSys.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBsUserComm<M extends BaseBsUserComm<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setCommModel(java.lang.String commModel) {
		set("COMM_MODEL", commModel);
		return (M)this;
	}
	
	public java.lang.String getCommModel() {
		return getStr("COMM_MODEL");
	}

	public M setFkTableId(java.lang.String fkTableId) {
		set("FK_TABLE_ID", fkTableId);
		return (M)this;
	}
	
	public java.lang.String getFkTableId() {
		return getStr("FK_TABLE_ID");
	}

	public M setFkBsUserSelf(java.lang.String fkBsUserSelf) {
		set("FK_BS_USER_SELF", fkBsUserSelf);
		return (M)this;
	}
	
	public java.lang.String getFkBsUserSelf() {
		return getStr("FK_BS_USER_SELF");
	}

	public M setFkBsUserComm(java.lang.String fkBsUserComm) {
		set("FK_BS_USER_COMM", fkBsUserComm);
		return (M)this;
	}
	
	public java.lang.String getFkBsUserComm() {
		return getStr("FK_BS_USER_COMM");
	}

	public M setFkBsComm(java.lang.String fkBsComm) {
		set("FK_BS_COMM", fkBsComm);
		return (M)this;
	}
	
	public java.lang.String getFkBsComm() {
		return getStr("FK_BS_COMM");
	}

	public M setCommContant(java.lang.String commContant) {
		set("COMM_CONTANT", commContant);
		return (M)this;
	}
	
	public java.lang.String getCommContant() {
		return getStr("COMM_CONTANT");
	}

	public M setLastCommContant(java.lang.String lastCommContant) {
		set("LAST_COMM_CONTANT", lastCommContant);
		return (M)this;
	}
	
	public java.lang.String getLastCommContant() {
		return getStr("LAST_COMM_CONTANT");
	}

	public M setCommTime(java.lang.String commTime) {
		set("COMM_TIME", commTime);
		return (M)this;
	}
	
	public java.lang.String getCommTime() {
		return getStr("COMM_TIME");
	}

	public M setCommIp(java.lang.String commIp) {
		set("COMM_IP", commIp);
		return (M)this;
	}
	
	public java.lang.String getCommIp() {
		return getStr("COMM_IP");
	}

	public M setCommType(java.lang.String commType) {
		set("COMM_TYPE", commType);
		return (M)this;
	}
	
	public java.lang.String getCommType() {
		return getStr("COMM_TYPE");
	}

	public M setCommOrder(java.lang.Integer commOrder) {
		set("COMM_ORDER", commOrder);
		return (M)this;
	}
	
	public java.lang.Integer getCommOrder() {
		return getInt("COMM_ORDER");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("CREATE_TIME", createTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return getStr("CREATE_TIME");
	}

	public M setCreateUserId(java.lang.String createUserId) {
		set("CREATE_USER_ID", createUserId);
		return (M)this;
	}
	
	public java.lang.String getCreateUserId() {
		return getStr("CREATE_USER_ID");
	}

	public M setModifyTime(java.lang.String modifyTime) {
		set("MODIFY_TIME", modifyTime);
		return (M)this;
	}
	
	public java.lang.String getModifyTime() {
		return getStr("MODIFY_TIME");
	}

	public M setModifyUserId(java.lang.String modifyUserId) {
		set("MODIFY_USER_ID", modifyUserId);
		return (M)this;
	}
	
	public java.lang.String getModifyUserId() {
		return getStr("MODIFY_USER_ID");
	}

}
