package com.black.blog.back.blogSys.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBsPhotoSort<M extends BaseBsPhotoSort<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setFkBsUser(java.lang.String fkBsUser) {
		set("FK_BS_USER", fkBsUser);
		return (M)this;
	}
	
	public java.lang.String getFkBsUser() {
		return getStr("FK_BS_USER");
	}

	public M setSortName(java.lang.String sortName) {
		set("SORT_NAME", sortName);
		return (M)this;
	}
	
	public java.lang.String getSortName() {
		return getStr("SORT_NAME");
	}

	public M setShowType(java.lang.String showType) {
		set("SHOW_TYPE", showType);
		return (M)this;
	}
	
	public java.lang.String getShowType() {
		return getStr("SHOW_TYPE");
	}

	public M setSortPwd(java.lang.String sortPwd) {
		set("SORT_PWD", sortPwd);
		return (M)this;
	}
	
	public java.lang.String getSortPwd() {
		return getStr("SORT_PWD");
	}

	public M setSortQuestion(java.lang.String sortQuestion) {
		set("SORT_QUESTION", sortQuestion);
		return (M)this;
	}
	
	public java.lang.String getSortQuestion() {
		return getStr("SORT_QUESTION");
	}

	public M setSortAnswer(java.lang.String sortAnswer) {
		set("SORT_ANSWER", sortAnswer);
		return (M)this;
	}
	
	public java.lang.String getSortAnswer() {
		return getStr("SORT_ANSWER");
	}

	public M setTopPicPath(java.lang.String topPicPath) {
		set("TOP_PIC_PATH", topPicPath);
		return (M)this;
	}
	
	public java.lang.String getTopPicPath() {
		return getStr("TOP_PIC_PATH");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("CREATE_TIME", createTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return getStr("CREATE_TIME");
	}

	public M setCreateUserId(java.lang.String createUserId) {
		set("CREATE_USER_ID", createUserId);
		return (M)this;
	}
	
	public java.lang.String getCreateUserId() {
		return getStr("CREATE_USER_ID");
	}

	public M setModifyTime(java.lang.String modifyTime) {
		set("MODIFY_TIME", modifyTime);
		return (M)this;
	}
	
	public java.lang.String getModifyTime() {
		return getStr("MODIFY_TIME");
	}

	public M setModifyUserId(java.lang.String modifyUserId) {
		set("MODIFY_USER_ID", modifyUserId);
		return (M)this;
	}
	
	public java.lang.String getModifyUserId() {
		return getStr("MODIFY_USER_ID");
	}

}
