package com.black.blog.back.blogSys.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBsGroup<M extends BaseBsGroup<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setGroupName(java.lang.String groupName) {
		set("GROUP_NAME", groupName);
		return (M)this;
	}
	
	public java.lang.String getGroupName() {
		return getStr("GROUP_NAME");
	}

}
