package com.black.blog.back.blogSys.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBsRank<M extends BaseBsRank<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setRankMark(java.lang.Integer rankMark) {
		set("RANK_MARK", rankMark);
		return (M)this;
	}
	
	public java.lang.Integer getRankMark() {
		return getInt("RANK_MARK");
	}

	public M setRankName(java.lang.String rankName) {
		set("RANK_NAME", rankName);
		return (M)this;
	}
	
	public java.lang.String getRankName() {
		return getStr("RANK_NAME");
	}

}
