package com.black.blog.back.blogSys.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBsAd<M extends BaseBsAd<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setAdPosition(java.lang.String adPosition) {
		set("AD_POSITION", adPosition);
		return (M)this;
	}
	
	public java.lang.String getAdPosition() {
		return getStr("AD_POSITION");
	}

	public M setAdOrder(java.lang.Integer adOrder) {
		set("AD_ORDER", adOrder);
		return (M)this;
	}
	
	public java.lang.Integer getAdOrder() {
		return getInt("AD_ORDER");
	}

	public M setTopStatus(java.lang.String topStatus) {
		set("TOP_STATUS", topStatus);
		return (M)this;
	}
	
	public java.lang.String getTopStatus() {
		return getStr("TOP_STATUS");
	}

	public M setAdType(java.lang.String adType) {
		set("AD_TYPE", adType);
		return (M)this;
	}
	
	public java.lang.String getAdType() {
		return getStr("AD_TYPE");
	}

	public M setAdName(java.lang.String adName) {
		set("AD_NAME", adName);
		return (M)this;
	}
	
	public java.lang.String getAdName() {
		return getStr("AD_NAME");
	}

	public M setLinkAddr(java.lang.String linkAddr) {
		set("LINK_ADDR", linkAddr);
		return (M)this;
	}
	
	public java.lang.String getLinkAddr() {
		return getStr("LINK_ADDR");
	}

	public M setContactMan(java.lang.String contactMan) {
		set("CONTACT_MAN", contactMan);
		return (M)this;
	}
	
	public java.lang.String getContactMan() {
		return getStr("CONTACT_MAN");
	}

	public M setContactEmail(java.lang.String contactEmail) {
		set("CONTACT_EMAIL", contactEmail);
		return (M)this;
	}
	
	public java.lang.String getContactEmail() {
		return getStr("CONTACT_EMAIL");
	}

	public M setContactPhone(java.lang.String contactPhone) {
		set("CONTACT_PHONE", contactPhone);
		return (M)this;
	}
	
	public java.lang.String getContactPhone() {
		return getStr("CONTACT_PHONE");
	}

	public M setClickNum(java.lang.Integer clickNum) {
		set("CLICK_NUM", clickNum);
		return (M)this;
	}
	
	public java.lang.Integer getClickNum() {
		return getInt("CLICK_NUM");
	}

	public M setUseStatus(java.lang.String useStatus) {
		set("USE_STATUS", useStatus);
		return (M)this;
	}
	
	public java.lang.String getUseStatus() {
		return getStr("USE_STATUS");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("CREATE_TIME", createTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return getStr("CREATE_TIME");
	}

	public M setCreateUserId(java.lang.String createUserId) {
		set("CREATE_USER_ID", createUserId);
		return (M)this;
	}
	
	public java.lang.String getCreateUserId() {
		return getStr("CREATE_USER_ID");
	}

	public M setModifyTime(java.lang.String modifyTime) {
		set("MODIFY_TIME", modifyTime);
		return (M)this;
	}
	
	public java.lang.String getModifyTime() {
		return getStr("MODIFY_TIME");
	}

	public M setModifyUserId(java.lang.String modifyUserId) {
		set("MODIFY_USER_ID", modifyUserId);
		return (M)this;
	}
	
	public java.lang.String getModifyUserId() {
		return getStr("MODIFY_USER_ID");
	}

}
